#!/bin/sh

riverctl spawn "dbus-update-activation-environment DBUS_SESSION_BUS_ADDRESS SEATD_SOCK DISPLAY WAYLAND_DISPLAY XAUTHORITY XDG_CURRECT_DESKTOP=river KITTY_ENABLE_WAYLAND"
riverctl spawn "gentoo-pipewire-launcher &"
riverctl spawn "wlr-randr --output DP-1 --mode 1920x1080@165.003006Hz --transform 90 --pos 0,0 --on --output DP-2 --mode 1920x1080@165.003006Hz --transform normal --pos 1080,420 --on"
riverctl spawn "swaybg -o DP-1 -m tile -i ~/wallpaper-ophelia.jpg -o DP-2 -m fill -i ~/wallpaper-ophelia.jpg &"

riverctl attach-mode bottom

riverctl focus-follows-cursor normal
riverctl set-cursor-wrap on-focus-change
riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enable

riverctl map normal Super Q close
riverctl map normal Super+Shift E exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super Return zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal

for mode in normal locked
do
    riverctl map $mode None XF86Eject spawn 'eject -T'

    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer set "Master" 10%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer set "Master" 10%-'
    riverctl map $mode None XF86AudioMute         spawn 'amixer set "Master" toggle'

    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

riverctl border-width 0
riverctl background-color 0xe5e4e2
riverctl border-color-focused 0xd1d0d1
riverctl border-color-unfocused 0x3e3e3e

riverctl set-repeat 50 300
riverctl keyboard-layout pl

riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id "bar" csd

riverctl default-layout rivertile
rivertile -view-padding 2 -outer-padding 1 -main-ratio 0.5 &

riverctl map normal None Print spawn "grim - | wl-copy"

# Screenshot area to clipboard
riverctl map normal Control Print spawn 'grim -g "$(slurp)" - | wl-copy'

# Screenshot display and save to $HOME/Pictures
riverctl map normal Alt Print spawn "grim $HOME/Pictures/$(date +'%s.png')"

# Screenshot area and save to $HOME/Pictures
riverctl map normal Alt+Control Print spawn 'grim -g "$(slurp)" $HOME/Pictures/$(date +'%s.png')'

riverctl map normal Super D spawn "rofi -show drun"
riverctl map normal Super W spawn qutebrowser
riverctl map normal Super T spawn kitty
riverctl map normal Super Return spawn kitty
